Use include directive in IWYU mappings
This is less portable, but also less work to maintain. It already wasn't
portable and couldn't be used on Travis as it was. A few symbols are
given explicitly to resolve remaining issues.

This also adds enforcement to keep to mapping sorted, for tidiness.

diff --git a/statictest/check_iwyu b/statictest/check_iwyu
--- a/statictest/check_iwyu
+++ b/statictest/check_iwyu
@@ -4,8 +4,14 @@
 
 . "${BASH_SOURCE%/*}/common.sh"
 
+if ! tail -n +2 "$COMMONDIR/iwyu.imp" | sort -C ; then
+	printf "${RED}Error:${NC} IWYU mapping not sorted.\n\n"
+	IWYU_NOTSORT=1
+fi
+
 check_iwyu_single () {
     [ "$TRAVIS" = true ] && return
+		[ -n "$IWYU_NOTSORT" ] && return 1
     file=$1
     if [[ "$file" = *.c ]] ; then
         lang_flags=(--language=c -std=c11)
